#Deploy MongoDB

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-conv
spec:
  selector:
    matchLabels:
      app: web-conv
  template:
    metadata:
      labels:
        app: web-conv
    spec:
      containers:
      - name: web-conv
        image: vazevedo96/conversao-temperatura:v1
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: web-conv
spec:
  selector:
    app: web-conv
  ports:
  - port: 8080
    nodePort: 30000
  type: LoadBalancer